// fp_mult_accumulate.v

// Generated using ACDS version 16.0 211

`timescale 1 ps / 1 ps
module fp_mult_accumulate (
		input  wire        accumulate, // accumulate.accumulate
		input  wire        aclr,       //       aclr.aclr
		input  wire [31:0] ay,         //         ay.ay
		input  wire [31:0] az,         //         az.az
		input  wire        clk,        //        clk.clk
		input  wire        ena,        //        ena.ena
		output wire [31:0] result      //     result.result
	);

	fp_mult_accumulate_altera_fpdsp_block_160_pjjncdi fpdsp_block_0 (
		.clk        (clk),        //        clk.clk
		.ena        (ena),        //        ena.ena
		.aclr       (aclr),       //       aclr.aclr
		.result     (result),     //     result.result
		.accumulate (accumulate), // accumulate.accumulate
		.ay         (ay),         //         ay.ay
		.az         (az)          //         az.az
	);

endmodule
