+incdir+./generic_fifos/rtl/verilog
+incdir+./buffers
+incdir+./state_machines
+incdir+../../../base/hw/rtl
+incdir+${FPGA_BBB_CCI_SRC}/BBB_cci_mpf/hw/rtl/cci-mpf-if/
// to avoid error
+incdir+/home/daniel/Desktop/transparent-acceleration/OPAE_Development/OPAE_Test/build_sim/rtl/
${FPGA_BBB_CCI_SRC}/BBB_cci_mpf/hw/rtl/cci-mpf-if/cci_mpf_if.vh
// to avoid error
/home/daniel/Desktop/transparent-acceleration/OPAE_Development/OPAE_Test/build_sim/rtl/afu_json_info.vh
./cci_mpf_app_conf.vh
./generic_fifos/bench/verilog/test_bench_top.v
./generic_fifos/rtl/verilog/lfsr.v
./generic_fifos/rtl/verilog/generic_fifo_dc.v
./generic_fifos/rtl/verilog/generic_fifo_lfsr.v
./generic_fifos/rtl/verilog/generic_fifo_dc_gray.v
./generic_fifos/rtl/verilog/generic_fifo_sc_b.v
./generic_fifos/rtl/verilog/generic_fifo_sc_a.v
./generic_fifos/rtl/verilog/generic_dpram.v
./state_machines/buffer_to_mpf_SM_matrix.sv
./state_machines/mpf_to_buffer_SM_matrix.sv
./buffers/buffer_512_to_64.sv
./buffers/buffer_512_to_64_tb.sv
./buffers/buffer_64_to_512.sv
./buffers/buffer_64_to_512_tb.sv
./fp_mult_accumulate/fp_mult_accumulate/fp_mult_accumulate_bb.v
./fp_mult_accumulate/fp_mult_accumulate/sim/fp_mult_accumulate.v
//./fp_mult_accumulate/fp_mult_accumulate/altera_fpdsp_block_160/sim/fp_mult_accumulate_altera_fpdsp_block_160_4mzrtia.sv
//./fp_mult_accumulate/fp_mult_accumulate/altera_fpdsp_block_160/synth/fp_mult_accumulate_altera_fpdsp_block_160_4mzrtia.sv
./fp_mult_accumulate/fp_mult_accumulate/synth/fp_mult_accumulate.v
./fp_mult_accumulate/fp_mult_accumulate/greybox/fp_mult_accumulate.v
./fp_add/fp_add/fp_add_bb.v
./fp_add/fp_add/sim/fp_add.v
//./fp_mult_accumulate/fp_mult_accumulate/altera_fpdsp_block_160/sim/fp_mult_accumulate_altera_fpdsp_block_160_4mzrtia.sv
//./fp_mult_accumulate/fp_mult_accumulate/altera_fpdsp_block_160/synth/fp_mult_accumulate_altera_fpdsp_block_160_4mzrtia.sv
./fp_add/fp_add/synth/fp_add.v
./fp_add/fp_add/greybox/fp_add.v
./cci_mpf_matrix_mult_afu.sv

