+incdir+./generic_fifos/rtl/verilog

+incdir+${FPGA_BBB_CCI_SRC}/BBB_cci_mpf/hw/rtl/cci-mpf-if/
${FPGA_BBB_CCI_SRC}/BBB_cci_mpf/hw/rtl/cci-mpf-if/cci_mpf_if.vh
// to avoid error
+incdir+/home/daniel/Desktop/transparent-acceleration/OPAE_Development/OPAE_Test/build_sim/rtl/
// to avoid error
/home/daniel/Desktop/transparent-acceleration/OPAE_Development/OPAE_Test/build_sim/rtl/afu_json_info.vh
+incdir+../../../base/hw/rtl
../../../base/hw/rtl/csr_mgr.sv
../../../base/hw/rtl/csr_mgr.vh

./cci_mpf_app_conf.vh
./generic_fifos/bench/verilog/test_bench_top.v
./generic_fifos/rtl/verilog/lfsr.v
./generic_fifos/rtl/verilog/generic_fifo_dc.v
./generic_fifos/rtl/verilog/generic_fifo_lfsr.v
./generic_fifos/rtl/verilog/generic_fifo_dc_gray.v
./generic_fifos/rtl/verilog/generic_fifo_sc_b.v
./generic_fifos/rtl/verilog/generic_fifo_sc_a.v
./generic_fifos/rtl/verilog/generic_dpram.v
./buffers/buffer_512_to_64_tb.sv
./buffers/buffer_64_to_512_tb.sv
./buffers/buffer_512_to_64.sv
./buffers/buffer_64_to_512.sv
./state_machines/buffer_to_mpf_SM.sv
./state_machines/mpf_to_buffer_SM.sv
./cci_mpf_fft_afu.sv
./fft_ip/fft_ip/fft_ip_inst.v
./fft_ip/fft_ip/fft_ip_bb.v
./fft_ip/fft_ip/sim/fft_ip.v
./fft_ip/fft_ip/altera_fft_ii_160/sim/mentor/hyper_pipeline_interface.v
./fft_ip/fft_ip/altera_fft_ii_160/sim/mentor/counter_module.sv
./fft_ip/fft_ip/altera_fft_ii_160/sim/aldec/hyper_pipeline_interface.v
./fft_ip/fft_ip/altera_fft_ii_160/sim/aldec/counter_module.sv
./fft_ip/fft_ip/altera_fft_ii_160/sim/synopsys/hyper_pipeline_interface.v
./fft_ip/fft_ip/altera_fft_ii_160/sim/synopsys/counter_module.sv
./fft_ip/fft_ip/altera_fft_ii_160/sim/cadence/hyper_pipeline_interface.v
./fft_ip/fft_ip/altera_fft_ii_160/sim/cadence/counter_module.sv
./fft_ip/fft_ip/altera_fft_ii_160/sim/fft_ip_altera_fft_ii_160_jdm63cq.sv
./fft_ip/fft_ip/altera_fft_ii_160/synth/hyper_pipeline_interface.v
./fft_ip/fft_ip/altera_fft_ii_160/synth/counter_module.sv
./fft_ip/fft_ip/altera_fft_ii_160/synth/fft_ip_altera_fft_ii_160_jdm63cq.sv
./fft_ip/fft_ip/synth/fft_ip.v
./fft_ip/fft_ii_0_example_design/src/fft_ii_0_example_design_test_program.sv
./fft_ip/fft_ii_0_example_design/src/fft_ii_0_example_design_tb.v
./fft_ip/fft_ii_0_example_design/src/fft_ii_0_example_design.v
./fft_ip/fft_ii_0_example_design/src/verbosity_pkg.sv
./fft_ip/fft_ii_0_example_design/src/altera_avalon_clock_source.sv
./fft_ip/fft_ii_0_example_design/src/altera_avalon_reset_source.sv
./fft_ip/fft_ii_0_example_design/src/avalon_utilities_pkg.sv
./fft_ip/fft_ii_0_example_design/src/altera_avalon_st_source_bfm.sv
./fft_ip/fft_ii_0_example_design/src/altera_avalon_st_sink_bfm.sv
./fft_ip/fft_ii_0_example_design/src/mentor/hyper_pipeline_interface.v
./fft_ip/fft_ii_0_example_design/src/mentor/counter_module.sv
./fft_ip/fft_ii_0_example_design/src/aldec/hyper_pipeline_interface.v
./fft_ip/fft_ii_0_example_design/src/aldec/counter_module.sv
./fft_ip/fft_ii_0_example_design/src/synopsys/hyper_pipeline_interface.v
./fft_ip/fft_ii_0_example_design/src/synopsys/counter_module.sv
./fft_ip/fft_ii_0_example_design/src/cadence/hyper_pipeline_interface.v
./fft_ip/fft_ii_0_example_design/src/cadence/counter_module.sv
./fft_ip/fft_ii_0_example_design/src/fft_ii_0_example_design_altera_fft_ii_160_5xoeswi.sv
./fft_ip/fft_ip_tb/fft_ip_tb/sim/fft_ip_tb.v
./fft_ip/fft_ip_tb/fft_ip_tb/fft_ip_10/sim/fft_ip.v
./fft_ip/fft_ip_tb/fft_ip_tb/altera_avalon_clock_source_160/sim/verbosity_pkg.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_avalon_clock_source_160/sim/altera_avalon_clock_source.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_avalon_reset_source_160/sim/verbosity_pkg.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_avalon_reset_source_160/sim/altera_avalon_reset_source.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_conduit_bfm_160/sim/verbosity_pkg.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_conduit_bfm_160/sim/altera_conduit_bfm_160_oln7wka.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_conduit_bfm_160/sim/altera_conduit_bfm_160_3fqkqha.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_fft_ii_160/sim/mentor/hyper_pipeline_interface.v
./fft_ip/fft_ip_tb/fft_ip_tb/altera_fft_ii_160/sim/mentor/counter_module.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_fft_ii_160/sim/aldec/hyper_pipeline_interface.v
./fft_ip/fft_ip_tb/fft_ip_tb/altera_fft_ii_160/sim/aldec/counter_module.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_fft_ii_160/sim/synopsys/hyper_pipeline_interface.v
./fft_ip/fft_ip_tb/fft_ip_tb/altera_fft_ii_160/sim/synopsys/counter_module.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_fft_ii_160/sim/cadence/hyper_pipeline_interface.v
./fft_ip/fft_ip_tb/fft_ip_tb/altera_fft_ii_160/sim/cadence/counter_module.sv
./fft_ip/fft_ip_tb/fft_ip_tb/altera_fft_ii_160/sim/fft_ip_altera_fft_ii_160_jdm63cq.sv

